baseURL = 'http://gpederzani.github.io/'
languageCode = 'en-us'
title = 'Giulia Pederzani'
theme = "anatole"
enableEmoji = true

[params]
title = "Giulia Pederzani"
author = "Giulia Pederzani"
description = """
Postdoctoral researcher on 
cardiovascular modelling and cerebral perfusion
"""
profilePicture = "profile_pic.jpg"

[menu]

    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Publications"
    identifier = "publications"
    weight = 200
    url = "/publications"

    [[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 300
    url = "/projects"
